apiVersion: v1
kind: Service
metadata:
  labels:
    app: lang-docs
  name: lang-docs
  namespace: lang
spec:
  ports:
    - name: "8110"
      port: 8110
      targetPort: 8110
  selector:
    app: lang-docs
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lang-docs
  name: lang-docs
  namespace: lang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lang-docs
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lang-docs
    spec:
      priorityClassName: high-priority
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/pivotstudio/lang-docs:{{.build_tag}}
          name: lang-docs
          ports:
            - containerPort: 8110
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
      restartPolicy: Always
status: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lang-docs
  namespace: lang
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # 开启use-regex，启用path的正则匹配 
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # ratelimit
    nginx.ingress.kubernetes.io/limit-connections: "60"
    nginx.ingress.kubernetes.io/limit-rps: "60"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
      proxy_ssl_server_name on;
      proxy_ssl_name $host;
spec:
  rules:
    - host: lang.pivotstudio.cn
      http:
        paths:
        # 不同path转发到不同端口
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: lang-docs
                port: 
                  number: 8110
  tls:
  - secretName: pivot-tls-cert
    hosts:
      - lang.pivotstudio.cn

