coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 1%
    patch:
      default:
        # basic
        target: 50%
        threshold: 1%
ignore:
  - "src/lsp/mod.rs"
  - "src/lsp/helpers.rs"
  - "src/lsp/dispatcher.rs"
  - "src/main.rs"
  - "src/lsp/lspserver.rs"
  - "src/lsp/wasm.rs"
  - "src/lsp/wasm.rs"
  - "src/repl/editor.rs"
